export let ViewsEnum;

(function (ViewsEnum) {
  ViewsEnum["MAIN"] = "VIEW_MAIN";
  ViewsEnum["BONDAGE"] = "VIEW_BONDAGE";
  ViewsEnum["APPROVE"] = "VIEW_APPROVE";
  ViewsEnum["UNBONDAGE"] = "VIEW_UNBONDAGE";
  ViewsEnum["QUERY"] = "VIEW_QUERY";
  ViewsEnum["RESPONSE"] = "VIEW_RESPONSE";
  ViewsEnum["ORACLES"] = "VIEW_ORACLES";
  ViewsEnum["GET_ENDPOINT"] = "VIEW_GET_ENDPOINT";
  ViewsEnum["INIT_CURVE"] = "VIEW_INIT_CURVE";
  ViewsEnum["ENDPOINT_PARAMS"] = "VIEW_ENDPOINT_PARAMS";
  ViewsEnum["DELETE_ENDPOINT"] = "VIEW_DELETE_ENDPOINT";
  ViewsEnum["PROVIDER_PARAMS"] = "VIEW_PROVIDER_PARAMS";
  ViewsEnum["CREATE_PROVIDER"] = "VIEW_CREATE_PROVIDER";
  ViewsEnum["TEMPLATES"] = "VIEW_TEMPLATES";
  ViewsEnum["INIT_TOKEN_CURVE"] = "VIEW_INIT_TOKEN_CURVE";
  ViewsEnum["TOKEN_BONDAGE"] = "VIEW_TOKEN_BONDAGE";
  ViewsEnum["TOKEN_APPROVE"] = "VIEW_TOKEN_APPROVE";
  ViewsEnum["TOKEN_UNBONDAGE"] = "VIEW_TOKEN_UNBONDAGE";
  ViewsEnum["NEW_TOKEN_PROVIDER"] = "VIEW_NEW_TOKEN_PROVIDER";
  ViewsEnum["TOKEN_PROVIDERS_LIST"] = "VIEW_TOKEN_PROVIDERS_LIST";
})(ViewsEnum || (ViewsEnum = {}));